name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build release
        run: 7z a release.zip
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: release.zip